// Java Package calc is a proxy for talking to a Go program.
//   gobind -lang=java github.com/scarviz/gocalc/calc
//
// File is generated by gobind. Do not edit.
package go.calc;

import go.Seq;

public abstract class Calc {
    private Calc() {} // uninstantiable
    
    public static double Div(double val1, double val2) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        double _result;
        _in.writeFloat64(val1);
        _in.writeFloat64(val2);
        Seq.send(DESCRIPTOR, CALL_Div, _in, _out);
        _result = _out.readFloat64();
        return _result;
    }
    
    public static long Minus(long val1, long val2) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        long _result;
        _in.writeInt(val1);
        _in.writeInt(val2);
        Seq.send(DESCRIPTOR, CALL_Minus, _in, _out);
        _result = _out.readInt();
        return _result;
    }
    
    public static long Multi(long val1, long val2) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        long _result;
        _in.writeInt(val1);
        _in.writeInt(val2);
        Seq.send(DESCRIPTOR, CALL_Multi, _in, _out);
        _result = _out.readInt();
        return _result;
    }
    
    public static long Plus(long val1, long val2) {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        long _result;
        _in.writeInt(val1);
        _in.writeInt(val2);
        Seq.send(DESCRIPTOR, CALL_Plus, _in, _out);
        _result = _out.readInt();
        return _result;
    }
    
    private static final int CALL_Div = 1;
    private static final int CALL_Minus = 2;
    private static final int CALL_Multi = 3;
    private static final int CALL_Plus = 4;
    private static final String DESCRIPTOR = "calc";
}
